"""sync orm drift

Revision ID: 9c0191d5922a
Revises: 001_initial_tables
Create Date: 2026-04-22 19:13:46.292757
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '9c0191d5922a'
down_revision = '001_initial_tables'
branch_labels = None
depends_on = None


def _create_enum_types() -> None:
    """Create enum types up front so ALTER TYPE operations don't fail on fresh DBs."""
    bind = op.get_bind()
    postgresql.ENUM(
        'PENDING', 'APPROVED', 'REJECTED', 'EXPIRED',
        name='approval_status_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'FX', 'EQUITY', 'ETF', 'INDEX_PROXY', 'COMMODITY_PROXY', 'CRYPTO',
        name='asset_class_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'NONE', 'MACRO', 'EARNINGS', 'SECTOR_NEWS', 'COMMODITY_MOVE', 'CENTRAL_BANK', 'GEOPOLITICS',
        name='catalyst_type_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'PAPER', 'AUTO_LIVE', 'CONFIRM_LIVE',
        name='execution_mode_name_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'FX', 'EQUITY', 'ETF', 'INDEX_PROXY', 'COMMODITY_PROXY', 'CRYPTO',
        name='execution_policy_asset_class_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'PAPER', 'AUTO_LIVE', 'CONFIRM_LIVE',
        name='execution_policy_mode_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'INTRADAY', 'ONE_TO_THREE_DAYS', 'THREE_TO_TEN_DAYS',
        name='horizon_label_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'NEW', 'ACCEPTED', 'FILLED', 'CANCELED', 'REJECTED', 'CLOSED',
        name='order_status_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'OPEN', 'CLOSED',
        name='position_status_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'SIGNAL_ENGINE', 'CATALYST_CLASSIFIER', 'TRADE_REVIEWER',
        name='prompt_role_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'TREND', 'RANGE', 'BREAKOUT', 'HIGH_VOLATILITY', 'LOW_VOLATILITY', 'RISK_ON', 'RISK_OFF',
        name='regime_type_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'TREND_PULLBACK', 'BREAKOUT_CONFIRMATION', 'NEWS_CONTINUATION', 'NONE',
        name='setup_type_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'TREND', 'RANGE', 'BREAKOUT', 'HIGH_VOLATILITY', 'LOW_VOLATILITY', 'RISK_ON', 'RISK_OFF',
        name='signal_regime_type_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'CANDIDATE', 'RISK_APPROVED', 'RISK_BLOCKED', 'PENDING_USER_APPROVAL', 'USER_APPROVED',
        'USER_REJECTED', 'PAPER_SUBMITTED', 'PAPER_FILLED', 'LIVE_SUBMITTED', 'LIVE_FILLED',
        'CLOSED', 'EXPIRED',
        name='signal_status_enum',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'LONG', 'SHORT', 'FLAT',
        name='trade_direction_enum',
    ).create(bind, checkfirst=True)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_enum_types()
    op.add_column('approval_requests', sa.Column('signal_id', sa.UUID(), nullable=False))
    op.add_column('approval_requests', sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('approval_requests', sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('approval_requests', sa.Column('responded_by', sa.String(length=255), nullable=True))
    op.add_column('approval_requests', sa.Column('notes', sa.String(length=1000), nullable=True))
    op.add_column('approval_requests', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(
        "ALTER TABLE approval_requests ALTER COLUMN status TYPE approval_status_enum USING status::approval_status_enum"
    )
    op.drop_index(op.f('ix_approval_requests_risk_decision_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_timestamp'), table_name='approval_requests')
    op.drop_constraint(op.f('approval_requests_risk_decision_id_fkey'), 'approval_requests', type_='foreignkey')
    op.create_foreign_key(None, 'approval_requests', 'signals', ['signal_id'], ['id'])
    op.drop_column('approval_requests', 'timestamp')
    op.drop_column('approval_requests', 'expired_at')
    op.drop_column('approval_requests', 'risk_decision_id')
    op.drop_column('approval_requests', 'approved_at')
    op.drop_column('approval_requests', 'approved_by')
    op.drop_column('approval_requests', 'reason')
    op.add_column('assets', sa.Column('asset_class', sa.Enum('FX', 'EQUITY', 'ETF', 'INDEX_PROXY', 'COMMODITY_PROXY', 'CRYPTO', name='asset_class_enum'), nullable=False))
    op.add_column('assets', sa.Column('base_currency', sa.String(length=20), nullable=True))
    op.add_column('assets', sa.Column('quote_currency', sa.String(length=20), nullable=True))
    op.add_column('assets', sa.Column('exchange', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('sector', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('assets', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('assets', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.execute(
        "ALTER TABLE assets ALTER COLUMN is_active TYPE boolean USING is_active::boolean"
    )
    op.drop_index(op.f('ix_assets_is_active'), table_name='assets')
    op.drop_constraint(op.f('uq_assets_symbol'), 'assets', type_='unique')
    op.drop_constraint(op.f('uq_symbol_type'), 'assets', type_='unique')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.drop_column('assets', 'description')
    op.drop_column('assets', 'currency')
    op.drop_column('assets', 'asset_type')
    op.add_column('audit_logs', sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_column('audit_logs', 'actor')
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'action')
    op.drop_column('audit_logs', 'risk_level')
    op.drop_column('audit_logs', 'details')
    op.add_column('bars', sa.Column('ts', sa.DateTime(timezone=True), nullable=False))
    op.add_column('bars', sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False))
    op.add_column('bars', sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False))
    op.add_column('bars', sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False))
    op.add_column('bars', sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False))
    op.add_column('bars', sa.Column('vwap', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('bars', sa.Column('source', sa.String(length=100), nullable=True))
    op.alter_column('bars', 'volume',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=22, scale=8),
               nullable=True)
    op.drop_index(op.f('ix_bars_asset_id'), table_name='bars')
    op.drop_index(op.f('ix_bars_timeframe'), table_name='bars')
    op.drop_index(op.f('ix_bars_timestamp'), table_name='bars')
    op.drop_constraint(op.f('uq_asset_bar'), 'bars', type_='unique')
    op.create_index('ix_bars_asset_timeframe_ts', 'bars', ['asset_id', 'timeframe', 'ts'], unique=False)
    op.create_unique_constraint('uq_bars_asset_timeframe_ts', 'bars', ['asset_id', 'timeframe', 'ts'])
    op.drop_column('bars', 'timestamp')
    op.drop_column('bars', 'high_price')
    op.drop_column('bars', 'low_price')
    op.drop_column('bars', 'close_price')
    op.drop_column('bars', 'open_price')
    op.add_column('eval_cases', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('eval_cases', sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('eval_cases', sa.Column('expected_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('eval_cases', sa.Column('scoring_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('eval_cases', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('eval_cases', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('eval_cases', 'description')
    op.drop_column('eval_cases', 'end_date')
    op.drop_column('eval_cases', 'start_date')
    op.drop_column('eval_cases', 'assets')
    op.drop_column('eval_cases', 'parameters')
    op.add_column('eval_runs', sa.Column('provider_name', sa.String(length=100), nullable=True))
    op.add_column('eval_runs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('eval_runs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('eval_runs', sa.Column('summary_score', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('eval_runs', sa.Column('pass_rate', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('eval_runs', sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('eval_runs', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_index(op.f('ix_eval_runs_eval_case_id'), table_name='eval_runs')
    op.drop_constraint(op.f('eval_runs_eval_case_id_fkey'), 'eval_runs', type_='foreignkey')
    op.drop_column('eval_runs', 'num_trades')
    op.drop_column('eval_runs', 'win_rate')
    op.drop_column('eval_runs', 'max_drawdown_pct')
    op.drop_column('eval_runs', 'sharpe_ratio')
    op.drop_column('eval_runs', 'total_return_pct')
    op.drop_column('eval_runs', 'eval_case_id')
    op.drop_column('eval_runs', 'results')
    op.execute(
        "ALTER TABLE execution_modes ALTER COLUMN name TYPE execution_mode_name_enum USING name::execution_mode_name_enum"
    )
    op.execute(
        "ALTER TABLE execution_modes ALTER COLUMN is_active TYPE boolean USING is_active::boolean"
    )
    op.drop_index(op.f('ix_execution_modes_is_active'), table_name='execution_modes')
    op.drop_column('execution_modes', 'description')
    op.drop_column('execution_modes', 'allows_live_orders')
    op.drop_column('execution_modes', 'requires_approval')
    op.add_column('execution_policies', sa.Column('asset_class', sa.Enum('FX', 'EQUITY', 'ETF', 'INDEX_PROXY', 'COMMODITY_PROXY', 'CRYPTO', name='execution_policy_asset_class_enum'), nullable=False))
    op.add_column('execution_policies', sa.Column('mode', sa.Enum('PAPER', 'AUTO_LIVE', 'CONFIRM_LIVE', name='execution_policy_mode_enum'), nullable=False))
    op.add_column('execution_policies', sa.Column('allow_long', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('execution_policies', sa.Column('allow_short', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('execution_policies', sa.Column('allowed_timeframes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('execution_policies', sa.Column('requires_user_confirmation', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('execution_policies', sa.Column('paper_only', sa.Boolean(), server_default='true', nullable=False))
    op.drop_index(op.f('ix_execution_policies_is_active'), table_name='execution_policies')
    op.drop_constraint(op.f('uq_execution_policies_name'), 'execution_policies', type_='unique')
    op.drop_constraint(op.f('execution_policies_risk_profile_id_fkey'), 'execution_policies', type_='foreignkey')
    op.drop_constraint(op.f('execution_policies_execution_mode_id_fkey'), 'execution_policies', type_='foreignkey')
    op.drop_column('execution_policies', 'description')
    op.drop_column('execution_policies', 'execution_mode_id')
    op.drop_column('execution_policies', 'is_active')
    op.drop_column('execution_policies', 'name')
    op.drop_column('execution_policies', 'updated_at')
    op.drop_column('execution_policies', 'conditions')
    op.drop_column('execution_policies', 'risk_profile_id')
    op.drop_column('execution_policies', 'routing_logic')
    op.add_column('feature_snapshots', sa.Column('scan_ts', sa.DateTime(timezone=True), nullable=False))
    op.add_column('feature_snapshots', sa.Column('timeframe', sa.String(length=10), nullable=False))
    op.add_column('feature_snapshots', sa.Column('trend_score', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('feature_snapshots', sa.Column('momentum_score', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('feature_snapshots', sa.Column('volatility_score', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('feature_snapshots', sa.Column('liquidity_score', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('feature_snapshots', sa.Column('relative_strength_score', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('feature_snapshots', sa.Column('regime', sa.Enum('TREND', 'RANGE', 'BREAKOUT', 'HIGH_VOLATILITY', 'LOW_VOLATILITY', 'RISK_ON', 'RISK_OFF', name='regime_type_enum'), nullable=True))
    op.add_column('feature_snapshots', sa.Column('atr', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('feature_snapshots', sa.Column('rsi', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('feature_snapshots', sa.Column('ema_fast', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('feature_snapshots', sa.Column('ema_slow', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('feature_snapshots', sa.Column('adx', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('feature_snapshots', sa.Column('distance_from_high_pct', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('feature_snapshots', sa.Column('distance_from_low_pct', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('feature_snapshots', sa.Column('market_quality_flag', sa.String(length=50), nullable=True))
    op.add_column('feature_snapshots', sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_feature_snapshots_asset_id'), table_name='feature_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_timestamp'), table_name='feature_snapshots')
    op.create_index('ix_feature_snapshots_asset_timeframe_scan_ts', 'feature_snapshots', ['asset_id', 'timeframe', 'scan_ts'], unique=False)
    op.create_unique_constraint('uq_feature_snapshots_asset_timeframe_scan_ts', 'feature_snapshots', ['asset_id', 'timeframe', 'scan_ts'])
    op.drop_column('feature_snapshots', 'timestamp')
    op.drop_column('feature_snapshots', 'sma_20')
    op.drop_column('feature_snapshots', 'bb_middle')
    op.drop_column('feature_snapshots', 'bb_lower')
    op.drop_column('feature_snapshots', 'rsi_14')
    op.drop_column('feature_snapshots', 'sma_50')
    op.drop_column('feature_snapshots', 'volatility')
    op.drop_column('feature_snapshots', 'trend_strength')
    op.drop_column('feature_snapshots', 'atr_14')
    op.drop_column('feature_snapshots', 'bb_upper')
    op.drop_column('feature_snapshots', 'sma_200')
    op.drop_column('feature_snapshots', 'market_quality')
    op.drop_column('feature_snapshots', 'volume_ratio')
    op.drop_column('feature_snapshots', 'trend_direction')
    op.add_column('model_versions', sa.Column('provider_name', sa.String(length=100), nullable=False))
    op.add_column('model_versions', sa.Column('provider', sa.String(length=100), nullable=False))
    op.add_column('model_versions', sa.Column('model_name', sa.String(length=255), nullable=False))
    op.add_column('model_versions', sa.Column('alias_name', sa.String(length=255), nullable=True))
    op.add_column('model_versions', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('model_versions', sa.Column('top_p', sa.Float(), nullable=True))
    op.add_column('model_versions', sa.Column('max_output_tokens', sa.Integer(), nullable=True))
    op.add_column('model_versions', sa.Column('reasoning_level', sa.String(length=50), nullable=True))
    op.add_column('model_versions', sa.Column('supports_structured_output', sa.Boolean(), server_default='true', nullable=False))
    op.execute(
        "ALTER TABLE model_versions ALTER COLUMN is_active TYPE boolean USING is_active::boolean"
    )
    op.alter_column('model_versions', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_index(op.f('ix_model_versions_is_active'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_name'), table_name='model_versions')
    op.drop_column('model_versions', 'activated_at')
    op.drop_column('model_versions', 'name')
    op.drop_column('model_versions', 'model_path')
    op.drop_column('model_versions', 'version')
    op.drop_column('model_versions', 'model_hash')
    op.drop_column('model_versions', 'model_type')
    op.add_column('news_articles', sa.Column('provider_article_id', sa.String(length=255), nullable=True))
    op.add_column('news_articles', sa.Column('body_text', sa.Text(), nullable=True))
    op.add_column('news_articles', sa.Column('source_name', sa.String(length=255), nullable=True))
    op.add_column('news_articles', sa.Column('authors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('news_articles', sa.Column('tickers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('news_articles', sa.Column('sector_tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('news_articles', sa.Column('sentiment_provider', sa.String(length=100), nullable=True))
    op.add_column('news_articles', sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('news_articles', 'url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_index(op.f('ix_news_articles_asset_id'), table_name='news_articles')
    op.create_unique_constraint(None, 'news_articles', ['provider_article_id'])
    op.drop_constraint(op.f('news_articles_asset_id_fkey'), 'news_articles', type_='foreignkey')
    op.drop_column('news_articles', 'asset_id')
    op.drop_column('news_articles', 'source')
    op.drop_column('news_articles', 'sentiment')
    op.drop_column('news_articles', 'relevance_score')
    op.add_column('paper_fills', sa.Column('fill_ts', sa.DateTime(timezone=True), nullable=False))
    op.add_column('paper_fills', sa.Column('fill_price', sa.Numeric(precision=18, scale=8), nullable=False))
    op.add_column('paper_fills', sa.Column('fill_qty', sa.Numeric(precision=18, scale=8), nullable=False))
    op.add_column('paper_fills', sa.Column('slippage_bps', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('paper_fills', sa.Column('fee_amount', sa.Numeric(precision=18, scale=8), nullable=True))
    op.drop_index(op.f('ix_paper_fills_paper_order_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_timestamp'), table_name='paper_fills')
    op.drop_column('paper_fills', 'timestamp')
    op.drop_column('paper_fills', 'price')
    op.drop_column('paper_fills', 'quantity')
    op.drop_column('paper_fills', 'commission')
    op.add_column('paper_orders', sa.Column('signal_id', sa.UUID(), nullable=False))
    op.add_column('paper_orders', sa.Column('order_type', sa.String(length=50), nullable=False))
    op.add_column('paper_orders', sa.Column('side', sa.String(length=20), nullable=False))
    op.add_column('paper_orders', sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('paper_orders', sa.Column('notional', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('paper_orders', sa.Column('stop_price', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('paper_orders', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('paper_orders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('paper_orders', 'limit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.execute(
        "ALTER TABLE paper_orders ALTER COLUMN status TYPE order_status_enum USING status::order_status_enum"
    )
    op.drop_index(op.f('ix_paper_orders_asset_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_risk_decision_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_timestamp'), table_name='paper_orders')
    op.drop_constraint(op.f('paper_orders_risk_decision_id_fkey'), 'paper_orders', type_='foreignkey')
    op.drop_constraint(op.f('paper_orders_asset_id_fkey'), 'paper_orders', type_='foreignkey')
    op.create_foreign_key(None, 'paper_orders', 'signals', ['signal_id'], ['id'])
    op.drop_column('paper_orders', 'asset_id')
    op.drop_column('paper_orders', 'timestamp')
    op.drop_column('paper_orders', 'direction')
    op.drop_column('paper_orders', 'risk_decision_id')
    op.drop_column('paper_orders', 'filled_quantity')
    op.drop_column('paper_orders', 'filled_price')
    op.drop_column('paper_orders', 'quantity')
    op.drop_column('paper_orders', 'filled_at')
    op.add_column('pnl_snapshots', sa.Column('snapshot_ts', sa.DateTime(timezone=True), nullable=False))
    op.add_column('pnl_snapshots', sa.Column('equity', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('pnl_snapshots', sa.Column('cash', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('pnl_snapshots', sa.Column('gross_exposure', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('pnl_snapshots', sa.Column('net_exposure', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('pnl_snapshots', sa.Column('open_pnl', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('pnl_snapshots', sa.Column('closed_pnl', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('pnl_snapshots', sa.Column('drawdown_pct', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('pnl_snapshots', sa.Column('win_rate_rolling', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('pnl_snapshots', sa.Column('profit_factor_rolling', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('pnl_snapshots', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_pnl_snapshots_execution_mode'), table_name='pnl_snapshots')
    op.drop_index(op.f('ix_pnl_snapshots_timestamp'), table_name='pnl_snapshots')
    op.drop_constraint(op.f('uq_pnl_snapshots_timestamp'), 'pnl_snapshots', type_='unique')
    op.create_index(op.f('ix_pnl_snapshots_snapshot_ts'), 'pnl_snapshots', ['snapshot_ts'], unique=False)
    op.drop_column('pnl_snapshots', 'timestamp')
    op.drop_column('pnl_snapshots', 'num_losing_trades')
    op.drop_column('pnl_snapshots', 'num_open_positions')
    op.drop_column('pnl_snapshots', 'account_value')
    op.drop_column('pnl_snapshots', 'cash_available')
    op.drop_column('pnl_snapshots', 'realized_pnl')
    op.drop_column('pnl_snapshots', 'execution_mode')
    op.drop_column('pnl_snapshots', 'num_trades_today')
    op.drop_column('pnl_snapshots', 'max_drawdown_pct')
    op.drop_column('pnl_snapshots', 'daily_pnl')
    op.drop_column('pnl_snapshots', 'daily_return_pct')
    op.drop_column('pnl_snapshots', 'unrealized_pnl')
    op.drop_column('pnl_snapshots', 'num_winning_trades')
    op.drop_column('pnl_snapshots', 'total_pnl')
    op.add_column('positions', sa.Column('signal_id', sa.UUID(), nullable=True))
    op.add_column('positions', sa.Column('side', sa.String(length=20), nullable=False))
    op.add_column('positions', sa.Column('stop_price', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('positions', sa.Column('target_price', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('positions', sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('positions', sa.Column('close_reason', sa.String(length=255), nullable=True))
    op.add_column('positions', sa.Column('realized_pnl', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('positions', sa.Column('max_favorable_excursion', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('positions', sa.Column('max_adverse_excursion', sa.Numeric(precision=18, scale=8), nullable=True))
    op.execute(
        "ALTER TABLE positions ALTER COLUMN status TYPE position_status_enum USING status::position_status_enum"
    )
    op.alter_column('positions', 'avg_entry_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=8),
               nullable=True)
    op.alter_column('positions', 'current_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.alter_column('positions', 'opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('positions', 'unrealized_pnl',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.drop_index(op.f('ix_positions_asset_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_timestamp'), table_name='positions')
    op.create_foreign_key(None, 'positions', 'signals', ['signal_id'], ['id'])
    op.drop_column('positions', 'timestamp')
    op.drop_column('positions', 'direction')
    op.drop_column('positions', 'unrealized_pnl_pct')
    op.drop_column('positions', 'execution_mode')
    op.drop_column('positions', 'quantity')
    op.alter_column('prompt_versions', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.execute(
        "ALTER TABLE prompt_versions ALTER COLUMN role TYPE prompt_role_enum USING role::prompt_role_enum"
    )
    op.alter_column('prompt_versions', 'version',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.execute(
        "ALTER TABLE prompt_versions ALTER COLUMN schema_json TYPE jsonb USING schema_json::jsonb"
    )
    op.execute(
        "ALTER TABLE prompt_versions ALTER COLUMN is_active TYPE boolean USING is_active::boolean"
    )
    op.drop_index(op.f('ix_prompt_versions_is_active'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_name'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_role'), table_name='prompt_versions')
    op.create_unique_constraint('uq_prompt_versions_role_version', 'prompt_versions', ['role', 'version'])
    op.drop_column('prompt_versions', 'activated_at')
    op.add_column('quotes', sa.Column('ts', sa.DateTime(timezone=True), nullable=False))
    op.add_column('quotes', sa.Column('bid', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('quotes', sa.Column('ask', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('quotes', sa.Column('mid', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('quotes', sa.Column('spread_abs', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('quotes', sa.Column('source', sa.String(length=100), nullable=True))
    op.alter_column('quotes', 'spread_bps',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=8),
               existing_nullable=True)
    op.drop_index(op.f('ix_quotes_asset_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_timestamp'), table_name='quotes')
    op.create_index('ix_quotes_asset_ts', 'quotes', ['asset_id', 'ts'], unique=False)
    op.drop_column('quotes', 'timestamp')
    op.drop_column('quotes', 'ask_price')
    op.drop_column('quotes', 'ask_size')
    op.drop_column('quotes', 'mid_price')
    op.drop_column('quotes', 'bid_price')
    op.drop_column('quotes', 'bid_size')
    op.add_column('risk_decisions', sa.Column('blocked_reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('risk_decisions', sa.Column('position_risk_pct', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('risk_decisions', sa.Column('notional_allowed', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('risk_decisions', sa.Column('correlation_bucket', sa.String(length=100), nullable=True))
    op.add_column('risk_decisions', sa.Column('spread_ok', sa.Boolean(), nullable=True))
    op.add_column('risk_decisions', sa.Column('session_ok', sa.Boolean(), nullable=True))
    op.add_column('risk_decisions', sa.Column('drawdown_ok', sa.Boolean(), nullable=True))
    op.add_column('risk_decisions', sa.Column('cooldown_ok', sa.Boolean(), nullable=True))
    op.add_column('risk_decisions', sa.Column('decision_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        "ALTER TABLE risk_decisions ALTER COLUMN approved TYPE boolean USING approved::boolean"
    )
    op.execute(
        "ALTER TABLE risk_decisions ALTER COLUMN kill_switch_active TYPE boolean USING kill_switch_active::boolean"
    )
    op.drop_index(op.f('ix_risk_decisions_signal_id'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_timestamp'), table_name='risk_decisions')
    op.create_unique_constraint(None, 'risk_decisions', ['signal_id'])
    op.drop_constraint(op.f('risk_decisions_risk_profile_id_fkey'), 'risk_decisions', type_='foreignkey')
    op.drop_column('risk_decisions', 'market_quality_check')
    op.drop_column('risk_decisions', 'timestamp')
    op.drop_column('risk_decisions', 'capital_available')
    op.drop_column('risk_decisions', 'blocking_rule')
    op.drop_column('risk_decisions', 'cooldown_active')
    op.drop_column('risk_decisions', 'position_limit')
    op.drop_column('risk_decisions', 'correlation_check')
    op.drop_column('risk_decisions', 'drawdown_limit')
    op.drop_column('risk_decisions', 'risk_profile_id')
    op.drop_column('risk_decisions', 'spread_check')
    op.drop_column('risk_decisions', 'reason')
    op.add_column('risk_profiles', sa.Column('max_capital_allocated', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('risk_profiles', sa.Column('max_correlated_positions', sa.Integer(), nullable=True))
    op.add_column('risk_profiles', sa.Column('auto_trade_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('risk_profiles', sa.Column('confirm_before_trade_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('risk_profiles', sa.Column('kill_switch_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('risk_profiles', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('risk_profiles', 'max_risk_per_trade_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               nullable=True)
    op.alter_column('risk_profiles', 'max_daily_drawdown_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               nullable=True)
    op.alter_column('risk_profiles', 'max_open_positions',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=True)
    op.drop_index(op.f('ix_risk_profiles_is_active'), table_name='risk_profiles')
    op.drop_column('risk_profiles', 'description')
    op.drop_column('risk_profiles', 'max_correlated_bucket_exposure')
    op.drop_column('risk_profiles', 'min_signal_score')
    op.drop_column('risk_profiles', 'is_active')
    op.drop_column('risk_profiles', 'cooldown_after_3_losses_min')
    op.drop_column('risk_profiles', 'min_confidence')
    op.drop_column('risk_profiles', 'max_spread_bps_fx')
    op.drop_column('risk_profiles', 'max_spread_bps_equity')
    op.add_column('signals', sa.Column('feature_snapshot_id', sa.UUID(), nullable=True))
    op.add_column('signals', sa.Column('model_version_id', sa.UUID(), nullable=True))
    op.add_column('signals', sa.Column('provider_name', sa.String(length=100), nullable=True))
    op.add_column('signals', sa.Column('scan_ts', sa.DateTime(timezone=True), nullable=False))
    op.add_column('signals', sa.Column('timeframe', sa.String(length=10), nullable=False))
    op.add_column('signals', sa.Column('signal_status', sa.Enum('CANDIDATE', 'RISK_APPROVED', 'RISK_BLOCKED', 'PENDING_USER_APPROVAL', 'USER_APPROVED', 'USER_REJECTED', 'PAPER_SUBMITTED', 'PAPER_FILLED', 'LIVE_SUBMITTED', 'LIVE_FILLED', 'CLOSED', 'EXPIRED', name='signal_status_enum'), nullable=False))
    op.add_column('signals', sa.Column('setup_type', sa.Enum('TREND_PULLBACK', 'BREAKOUT_CONFIRMATION', 'NEWS_CONTINUATION', 'NONE', name='setup_type_enum'), nullable=False))
    op.add_column('signals', sa.Column('regime', sa.Enum('TREND', 'RANGE', 'BREAKOUT', 'HIGH_VOLATILITY', 'LOW_VOLATILITY', 'RISK_ON', 'RISK_OFF', name='signal_regime_type_enum'), nullable=True))
    op.add_column('signals', sa.Column('entry_min', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('signals', sa.Column('entry_max', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('signals', sa.Column('stop_price', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('signals', sa.Column('target_price', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('signals', sa.Column('horizon_label', sa.Enum('INTRADAY', 'ONE_TO_THREE_DAYS', 'THREE_TO_TEN_DAYS', name='horizon_label_enum'), nullable=True))
    op.add_column('signals', sa.Column('catalyst_type', sa.Enum('NONE', 'MACRO', 'EARNINGS', 'SECTOR_NEWS', 'COMMODITY_MOVE', 'CENTRAL_BANK', 'GEOPOLITICS', name='catalyst_type_enum'), nullable=True))
    op.add_column('signals', sa.Column('catalyst_score', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('signals', sa.Column('catalyst_summary', sa.Text(), nullable=True))
    op.add_column('signals', sa.Column('thesis', sa.Text(), nullable=True))
    op.add_column('signals', sa.Column('invalidators_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('signals', sa.Column('raw_llm_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute(
        "ALTER TABLE signals ALTER COLUMN direction TYPE trade_direction_enum USING direction::trade_direction_enum"
    )
    op.alter_column('signals', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               nullable=True)
    op.alter_column('signals', 'signal_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=4),
               nullable=True)
    op.drop_index(op.f('ix_signals_asset_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_timestamp'), table_name='signals')
    op.create_index('ix_signals_asset_scan_ts', 'signals', ['asset_id', 'scan_ts'], unique=False)
    op.create_index('ix_signals_status_scan_ts', 'signals', ['signal_status', 'scan_ts'], unique=False)
    op.create_foreign_key(None, 'signals', 'feature_snapshots', ['feature_snapshot_id'], ['id'])
    op.create_foreign_key(None, 'signals', 'model_versions', ['model_version_id'], ['id'])
    op.drop_column('signals', 'catalyst')
    op.drop_column('signals', 'timestamp')
    op.drop_column('signals', 'catalyst_strength')
    op.drop_column('signals', 'reasoning')
    op.drop_column('signals', 'is_actionable')
    op.drop_column('signals', 'structured_output')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('structured_output', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('signals', sa.Column('is_actionable', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('signals', sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('signals', sa.Column('catalyst_strength', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('signals', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('signals', sa.Column('catalyst', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'signals', type_='foreignkey')
    op.drop_constraint(None, 'signals', type_='foreignkey')
    op.drop_index('ix_signals_status_scan_ts', table_name='signals')
    op.drop_index('ix_signals_asset_scan_ts', table_name='signals')
    op.create_index(op.f('ix_signals_timestamp'), 'signals', ['timestamp'], unique=False)
    op.create_index(op.f('ix_signals_asset_id'), 'signals', ['asset_id'], unique=False)
    op.alter_column('signals', 'signal_score',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('signals', 'confidence',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('signals', 'direction',
               existing_type=sa.Enum('LONG', 'SHORT', 'FLAT', name='trade_direction_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('signals', 'raw_llm_json')
    op.drop_column('signals', 'invalidators_json')
    op.drop_column('signals', 'thesis')
    op.drop_column('signals', 'catalyst_summary')
    op.drop_column('signals', 'catalyst_score')
    op.drop_column('signals', 'catalyst_type')
    op.drop_column('signals', 'horizon_label')
    op.drop_column('signals', 'target_price')
    op.drop_column('signals', 'stop_price')
    op.drop_column('signals', 'entry_max')
    op.drop_column('signals', 'entry_min')
    op.drop_column('signals', 'regime')
    op.drop_column('signals', 'setup_type')
    op.drop_column('signals', 'signal_status')
    op.drop_column('signals', 'timeframe')
    op.drop_column('signals', 'scan_ts')
    op.drop_column('signals', 'provider_name')
    op.drop_column('signals', 'model_version_id')
    op.drop_column('signals', 'feature_snapshot_id')
    op.add_column('risk_profiles', sa.Column('max_spread_bps_equity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('risk_profiles', sa.Column('max_spread_bps_fx', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('risk_profiles', sa.Column('min_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('risk_profiles', sa.Column('cooldown_after_3_losses_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('risk_profiles', sa.Column('is_active', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('risk_profiles', sa.Column('min_signal_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('risk_profiles', sa.Column('max_correlated_bucket_exposure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('risk_profiles', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_risk_profiles_is_active'), 'risk_profiles', ['is_active'], unique=False)
    op.alter_column('risk_profiles', 'max_open_positions',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('risk_profiles', 'max_daily_drawdown_pct',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('risk_profiles', 'max_risk_per_trade_pct',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('risk_profiles', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('risk_profiles', 'kill_switch_enabled')
    op.drop_column('risk_profiles', 'confirm_before_trade_enabled')
    op.drop_column('risk_profiles', 'auto_trade_enabled')
    op.drop_column('risk_profiles', 'max_correlated_positions')
    op.drop_column('risk_profiles', 'max_capital_allocated')
    op.add_column('risk_decisions', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('risk_decisions', sa.Column('spread_check', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('risk_decisions', sa.Column('risk_profile_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('risk_decisions', sa.Column('drawdown_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('risk_decisions', sa.Column('correlation_check', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('risk_decisions', sa.Column('position_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('risk_decisions', sa.Column('cooldown_active', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('risk_decisions', sa.Column('blocking_rule', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('risk_decisions', sa.Column('capital_available', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('risk_decisions', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('risk_decisions', sa.Column('market_quality_check', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('risk_decisions_risk_profile_id_fkey'), 'risk_decisions', 'risk_profiles', ['risk_profile_id'], ['id'])
    op.drop_constraint(None, 'risk_decisions', type_='unique')
    op.create_index(op.f('ix_risk_decisions_timestamp'), 'risk_decisions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_risk_decisions_signal_id'), 'risk_decisions', ['signal_id'], unique=False)
    op.alter_column('risk_decisions', 'kill_switch_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('risk_decisions', 'approved',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('risk_decisions', 'decision_json')
    op.drop_column('risk_decisions', 'cooldown_ok')
    op.drop_column('risk_decisions', 'drawdown_ok')
    op.drop_column('risk_decisions', 'session_ok')
    op.drop_column('risk_decisions', 'spread_ok')
    op.drop_column('risk_decisions', 'correlation_bucket')
    op.drop_column('risk_decisions', 'notional_allowed')
    op.drop_column('risk_decisions', 'position_risk_pct')
    op.drop_column('risk_decisions', 'blocked_reasons_json')
    op.add_column('quotes', sa.Column('bid_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('bid_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('mid_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('quotes', sa.Column('ask_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('ask_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index('ix_quotes_asset_ts', table_name='quotes')
    op.create_index(op.f('ix_quotes_timestamp'), 'quotes', ['timestamp'], unique=False)
    op.create_index(op.f('ix_quotes_asset_id'), 'quotes', ['asset_id'], unique=False)
    op.alter_column('quotes', 'spread_bps',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('quotes', 'source')
    op.drop_column('quotes', 'spread_abs')
    op.drop_column('quotes', 'mid')
    op.drop_column('quotes', 'ask')
    op.drop_column('quotes', 'bid')
    op.drop_column('quotes', 'ts')
    op.add_column('prompt_versions', sa.Column('activated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint('uq_prompt_versions_role_version', 'prompt_versions', type_='unique')
    op.create_index(op.f('ix_prompt_versions_role'), 'prompt_versions', ['role'], unique=False)
    op.create_index(op.f('ix_prompt_versions_name'), 'prompt_versions', ['name'], unique=False)
    op.create_index(op.f('ix_prompt_versions_is_active'), 'prompt_versions', ['is_active'], unique=False)
    op.alter_column('prompt_versions', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('prompt_versions', 'schema_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('prompt_versions', 'version',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('prompt_versions', 'role',
               existing_type=sa.Enum('SIGNAL_ENGINE', 'CATALYST_CLASSIFIER', 'TRADE_REVIEWER', name='prompt_role_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('prompt_versions', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('positions', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('positions', sa.Column('execution_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('positions', sa.Column('unrealized_pnl_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('positions', sa.Column('direction', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('positions', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.create_index(op.f('ix_positions_timestamp'), 'positions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_positions_asset_id'), 'positions', ['asset_id'], unique=False)
    op.alter_column('positions', 'unrealized_pnl',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('positions', 'opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('positions', 'current_price',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('positions', 'avg_entry_price',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('positions', 'status',
               existing_type=sa.Enum('OPEN', 'CLOSED', name='position_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('positions', 'max_adverse_excursion')
    op.drop_column('positions', 'max_favorable_excursion')
    op.drop_column('positions', 'realized_pnl')
    op.drop_column('positions', 'close_reason')
    op.drop_column('positions', 'qty')
    op.drop_column('positions', 'target_price')
    op.drop_column('positions', 'stop_price')
    op.drop_column('positions', 'side')
    op.drop_column('positions', 'signal_id')
    op.add_column('pnl_snapshots', sa.Column('total_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('num_winning_trades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('unrealized_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('daily_return_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('daily_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('max_drawdown_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('num_trades_today', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('execution_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('realized_pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('cash_available', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('account_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('num_open_positions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('num_losing_trades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('pnl_snapshots', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_pnl_snapshots_snapshot_ts'), table_name='pnl_snapshots')
    op.create_unique_constraint(op.f('uq_pnl_snapshots_timestamp'), 'pnl_snapshots', ['timestamp'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pnl_snapshots_timestamp'), 'pnl_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_pnl_snapshots_execution_mode'), 'pnl_snapshots', ['execution_mode'], unique=False)
    op.drop_column('pnl_snapshots', 'metadata_json')
    op.drop_column('pnl_snapshots', 'profit_factor_rolling')
    op.drop_column('pnl_snapshots', 'win_rate_rolling')
    op.drop_column('pnl_snapshots', 'drawdown_pct')
    op.drop_column('pnl_snapshots', 'closed_pnl')
    op.drop_column('pnl_snapshots', 'open_pnl')
    op.drop_column('pnl_snapshots', 'net_exposure')
    op.drop_column('pnl_snapshots', 'gross_exposure')
    op.drop_column('pnl_snapshots', 'cash')
    op.drop_column('pnl_snapshots', 'equity')
    op.drop_column('pnl_snapshots', 'snapshot_ts')
    op.add_column('paper_orders', sa.Column('filled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('paper_orders', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('paper_orders', sa.Column('filled_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('paper_orders', sa.Column('filled_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('paper_orders', sa.Column('risk_decision_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('paper_orders', sa.Column('direction', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('paper_orders', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('paper_orders', sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'paper_orders', type_='foreignkey')
    op.create_foreign_key(op.f('paper_orders_asset_id_fkey'), 'paper_orders', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key(op.f('paper_orders_risk_decision_id_fkey'), 'paper_orders', 'risk_decisions', ['risk_decision_id'], ['id'])
    op.create_index(op.f('ix_paper_orders_timestamp'), 'paper_orders', ['timestamp'], unique=False)
    op.create_index(op.f('ix_paper_orders_risk_decision_id'), 'paper_orders', ['risk_decision_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_asset_id'), 'paper_orders', ['asset_id'], unique=False)
    op.alter_column('paper_orders', 'status',
               existing_type=sa.Enum('NEW', 'ACCEPTED', 'FILLED', 'CANCELED', 'REJECTED', 'CLOSED', name='order_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('paper_orders', 'limit_price',
               existing_type=sa.Numeric(precision=18, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('paper_orders', 'updated_at')
    op.drop_column('paper_orders', 'submitted_at')
    op.drop_column('paper_orders', 'stop_price')
    op.drop_column('paper_orders', 'notional')
    op.drop_column('paper_orders', 'qty')
    op.drop_column('paper_orders', 'side')
    op.drop_column('paper_orders', 'order_type')
    op.drop_column('paper_orders', 'signal_id')
    op.add_column('paper_fills', sa.Column('commission', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('paper_fills', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('paper_fills', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('paper_fills', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_paper_fills_timestamp'), 'paper_fills', ['timestamp'], unique=False)
    op.create_index(op.f('ix_paper_fills_paper_order_id'), 'paper_fills', ['paper_order_id'], unique=False)
    op.drop_column('paper_fills', 'fee_amount')
    op.drop_column('paper_fills', 'slippage_bps')
    op.drop_column('paper_fills', 'fill_qty')
    op.drop_column('paper_fills', 'fill_price')
    op.drop_column('paper_fills', 'fill_ts')
    op.add_column('news_articles', sa.Column('relevance_score', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('news_articles', sa.Column('sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('news_articles', sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('news_articles', sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('news_articles_asset_id_fkey'), 'news_articles', 'assets', ['asset_id'], ['id'])
    op.drop_constraint(None, 'news_articles', type_='unique')
    op.create_index(op.f('ix_news_articles_asset_id'), 'news_articles', ['asset_id'], unique=False)
    op.alter_column('news_articles', 'url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('news_articles', 'raw_json')
    op.drop_column('news_articles', 'sentiment_provider')
    op.drop_column('news_articles', 'sector_tags_json')
    op.drop_column('news_articles', 'tickers_json')
    op.drop_column('news_articles', 'authors_json')
    op.drop_column('news_articles', 'source_name')
    op.drop_column('news_articles', 'body_text')
    op.drop_column('news_articles', 'provider_article_id')
    op.add_column('model_versions', sa.Column('model_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('model_versions', sa.Column('model_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('model_versions', sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('model_versions', sa.Column('model_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('model_versions', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('model_versions', sa.Column('activated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_model_versions_name'), 'model_versions', ['name'], unique=False)
    op.create_index(op.f('ix_model_versions_is_active'), 'model_versions', ['is_active'], unique=False)
    op.alter_column('model_versions', 'notes',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('model_versions', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('model_versions', 'supports_structured_output')
    op.drop_column('model_versions', 'reasoning_level')
    op.drop_column('model_versions', 'max_output_tokens')
    op.drop_column('model_versions', 'top_p')
    op.drop_column('model_versions', 'temperature')
    op.drop_column('model_versions', 'alias_name')
    op.drop_column('model_versions', 'model_name')
    op.drop_column('model_versions', 'provider')
    op.drop_column('model_versions', 'provider_name')
    op.add_column('feature_snapshots', sa.Column('trend_direction', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('volume_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('market_quality', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('sma_200', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('bb_upper', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('atr_14', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('trend_strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('volatility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('sma_50', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('rsi_14', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('bb_lower', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('bb_middle', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('sma_20', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feature_snapshots', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('uq_feature_snapshots_asset_timeframe_scan_ts', 'feature_snapshots', type_='unique')
    op.drop_index('ix_feature_snapshots_asset_timeframe_scan_ts', table_name='feature_snapshots')
    op.create_index(op.f('ix_feature_snapshots_timestamp'), 'feature_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_asset_id'), 'feature_snapshots', ['asset_id'], unique=False)
    op.drop_column('feature_snapshots', 'features_json')
    op.drop_column('feature_snapshots', 'market_quality_flag')
    op.drop_column('feature_snapshots', 'distance_from_low_pct')
    op.drop_column('feature_snapshots', 'distance_from_high_pct')
    op.drop_column('feature_snapshots', 'adx')
    op.drop_column('feature_snapshots', 'ema_slow')
    op.drop_column('feature_snapshots', 'ema_fast')
    op.drop_column('feature_snapshots', 'rsi')
    op.drop_column('feature_snapshots', 'atr')
    op.drop_column('feature_snapshots', 'regime')
    op.drop_column('feature_snapshots', 'relative_strength_score')
    op.drop_column('feature_snapshots', 'liquidity_score')
    op.drop_column('feature_snapshots', 'volatility_score')
    op.drop_column('feature_snapshots', 'momentum_score')
    op.drop_column('feature_snapshots', 'trend_score')
    op.drop_column('feature_snapshots', 'timeframe')
    op.drop_column('feature_snapshots', 'scan_ts')
    op.add_column('execution_policies', sa.Column('routing_logic', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('execution_policies', sa.Column('risk_profile_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('execution_policies', sa.Column('conditions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('execution_policies', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('execution_policies', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('execution_policies', sa.Column('is_active', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('execution_policies', sa.Column('execution_mode_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('execution_policies', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('execution_policies_execution_mode_id_fkey'), 'execution_policies', 'execution_modes', ['execution_mode_id'], ['id'])
    op.create_foreign_key(op.f('execution_policies_risk_profile_id_fkey'), 'execution_policies', 'risk_profiles', ['risk_profile_id'], ['id'])
    op.create_unique_constraint(op.f('uq_execution_policies_name'), 'execution_policies', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_execution_policies_is_active'), 'execution_policies', ['is_active'], unique=False)
    op.drop_column('execution_policies', 'paper_only')
    op.drop_column('execution_policies', 'requires_user_confirmation')
    op.drop_column('execution_policies', 'allowed_timeframes_json')
    op.drop_column('execution_policies', 'allow_short')
    op.drop_column('execution_policies', 'allow_long')
    op.drop_column('execution_policies', 'mode')
    op.drop_column('execution_policies', 'asset_class')
    op.add_column('execution_modes', sa.Column('requires_approval', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('execution_modes', sa.Column('allows_live_orders', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('execution_modes', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_execution_modes_is_active'), 'execution_modes', ['is_active'], unique=False)
    op.alter_column('execution_modes', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('execution_modes', 'name',
               existing_type=sa.Enum('PAPER', 'AUTO_LIVE', 'CONFIRM_LIVE', name='execution_mode_name_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('eval_runs', sa.Column('results', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('eval_runs', sa.Column('eval_case_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('eval_runs', sa.Column('total_return_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('eval_runs', sa.Column('sharpe_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('eval_runs', sa.Column('max_drawdown_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('eval_runs', sa.Column('win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('eval_runs', sa.Column('num_trades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('eval_runs_eval_case_id_fkey'), 'eval_runs', 'eval_cases', ['eval_case_id'], ['id'])
    op.create_index(op.f('ix_eval_runs_eval_case_id'), 'eval_runs', ['eval_case_id'], unique=False)
    op.alter_column('eval_runs', 'notes',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('eval_runs', 'output_json')
    op.drop_column('eval_runs', 'pass_rate')
    op.drop_column('eval_runs', 'summary_score')
    op.drop_column('eval_runs', 'completed_at')
    op.drop_column('eval_runs', 'started_at')
    op.drop_column('eval_runs', 'provider_name')
    op.add_column('eval_cases', sa.Column('parameters', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('eval_cases', sa.Column('assets', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('eval_cases', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('eval_cases', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('eval_cases', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('eval_cases', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('eval_cases', 'is_active')
    op.drop_column('eval_cases', 'scoring_rules_json')
    op.drop_column('eval_cases', 'expected_json')
    op.drop_column('eval_cases', 'input_json')
    op.drop_column('eval_cases', 'category')
    op.add_column('bars', sa.Column('open_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('bars', sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('bars', sa.Column('low_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('bars', sa.Column('high_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('bars', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('uq_bars_asset_timeframe_ts', 'bars', type_='unique')
    op.drop_index('ix_bars_asset_timeframe_ts', table_name='bars')
    op.create_unique_constraint(op.f('uq_asset_bar'), 'bars', ['asset_id', 'timestamp', 'timeframe'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_bars_timestamp'), 'bars', ['timestamp'], unique=False)
    op.create_index(op.f('ix_bars_timeframe'), 'bars', ['timeframe'], unique=False)
    op.create_index(op.f('ix_bars_asset_id'), 'bars', ['asset_id'], unique=False)
    op.alter_column('bars', 'volume',
               existing_type=sa.Numeric(precision=22, scale=8),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_column('bars', 'source')
    op.drop_column('bars', 'vwap')
    op.drop_column('bars', 'close')
    op.drop_column('bars', 'low')
    op.drop_column('bars', 'high')
    op.drop_column('bars', 'open')
    op.drop_column('bars', 'ts')
    op.add_column('audit_logs', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('actor', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('audit_logs', 'payload_json')
    op.add_column('assets', sa.Column('asset_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_unique_constraint(op.f('uq_symbol_type'), 'assets', ['symbol', 'asset_type'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_assets_symbol'), 'assets', ['symbol'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_assets_is_active'), 'assets', ['is_active'], unique=False)
    op.alter_column('assets', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('assets', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('assets', 'symbol',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('assets', 'metadata_json')
    op.drop_column('assets', 'industry')
    op.drop_column('assets', 'sector')
    op.drop_column('assets', 'exchange')
    op.drop_column('assets', 'quote_currency')
    op.drop_column('assets', 'base_currency')
    op.drop_column('assets', 'asset_class')
    op.add_column('approval_requests', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('approval_requests', sa.Column('approved_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('approval_requests', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('approval_requests', sa.Column('risk_decision_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('approval_requests', sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('approval_requests', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'approval_requests', type_='foreignkey')
    op.create_foreign_key(op.f('approval_requests_risk_decision_id_fkey'), 'approval_requests', 'risk_decisions', ['risk_decision_id'], ['id'])
    op.create_index(op.f('ix_approval_requests_timestamp'), 'approval_requests', ['timestamp'], unique=False)
    op.create_index(op.f('ix_approval_requests_risk_decision_id'), 'approval_requests', ['risk_decision_id'], unique=False)
    op.alter_column('approval_requests', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approval_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('approval_requests', 'expires_at')
    op.drop_column('approval_requests', 'notes')
    op.drop_column('approval_requests', 'responded_by')
    op.drop_column('approval_requests', 'responded_at')
    op.drop_column('approval_requests', 'requested_at')
    op.drop_column('approval_requests', 'signal_id')
    # ### end Alembic commands ###
