"""add_missing_risk_decision_columns

Revision ID: d058936fdd0d
Revises: 9c0191d5922a
Create Date: 2026-04-24 09:27:44.275072
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'd058936fdd0d'
down_revision = '9c0191d5922a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('risk_decision_id', sa.UUID(), nullable=True))
    op.add_column('approval_requests', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('approval_requests', sa.Column('approved_by', sa.String(length=255), nullable=True))
    op.add_column('approval_requests', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('approval_requests', sa.Column('rejected_by', sa.String(length=255), nullable=True))
    op.add_column('approval_requests', sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('approval_requests', 'signal_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('approval_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approval_status_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('execution_modes', sa.Column('requires_approval', sa.String(length=20), server_default='inactive', nullable=False))
    op.add_column('execution_modes', sa.Column('allows_live_orders', sa.String(length=20), server_default='inactive', nullable=False))
    op.add_column('paper_orders', sa.Column('asset_id', sa.UUID(), nullable=True))
    op.add_column('paper_orders', sa.Column('risk_decision_id', sa.UUID(), nullable=True))
    op.add_column('paper_orders', sa.Column('direction', sa.String(length=20), nullable=True))
    op.add_column('paper_orders', sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('paper_orders', sa.Column('filled_quantity', sa.Numeric(precision=18, scale=8), server_default='0.0', nullable=False))
    op.add_column('paper_orders', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('paper_orders', 'signal_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('paper_orders', 'order_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('paper_orders', 'side',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('paper_orders', 'status',
               existing_type=postgresql.ENUM('NEW', 'ACCEPTED', 'FILLED', 'CANCELED', 'REJECTED', 'CLOSED', name='order_status_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('prompt_versions', 'schema_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.add_column('risk_decisions', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('risk_decisions', sa.Column('blocking_rule', sa.String(length=100), nullable=True))
    op.alter_column('risk_decisions', 'signal_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('risk_decisions', 'approved',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('risk_decisions', 'kill_switch_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('risk_decisions_signal_id_key'), 'risk_decisions', type_='unique')
    op.add_column('risk_profiles', sa.Column('is_active', sa.String(length=20), server_default='inactive', nullable=False))
    op.add_column('risk_profiles', sa.Column('max_correlated_bucket_exposure', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('risk_profiles', sa.Column('min_confidence', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('risk_profiles', sa.Column('min_signal_score', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('risk_profiles', sa.Column('max_spread_bps_fx', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('risk_profiles', sa.Column('max_spread_bps_equity', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('risk_profiles', sa.Column('cooldown_after_3_losses_min', sa.Numeric(precision=10, scale=4), nullable=True))
    op.alter_column('risk_profiles', 'max_open_positions',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('risk_profiles', 'max_correlated_positions',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_profiles', 'max_correlated_positions',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('risk_profiles', 'max_open_positions',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('risk_profiles', 'cooldown_after_3_losses_min')
    op.drop_column('risk_profiles', 'max_spread_bps_equity')
    op.drop_column('risk_profiles', 'max_spread_bps_fx')
    op.drop_column('risk_profiles', 'min_signal_score')
    op.drop_column('risk_profiles', 'min_confidence')
    op.drop_column('risk_profiles', 'max_correlated_bucket_exposure')
    op.drop_column('risk_profiles', 'is_active')
    op.create_unique_constraint(op.f('risk_decisions_signal_id_key'), 'risk_decisions', ['signal_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('risk_decisions', 'kill_switch_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('risk_decisions', 'approved',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.alter_column('risk_decisions', 'signal_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('risk_decisions', 'blocking_rule')
    op.drop_column('risk_decisions', 'timestamp')
    op.alter_column('prompt_versions', 'schema_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('paper_orders', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('NEW', 'ACCEPTED', 'FILLED', 'CANCELED', 'REJECTED', 'CLOSED', name='order_status_enum'),
               existing_nullable=False)
    op.alter_column('paper_orders', 'side',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('paper_orders', 'order_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('paper_orders', 'signal_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('paper_orders', 'timestamp')
    op.drop_column('paper_orders', 'filled_quantity')
    op.drop_column('paper_orders', 'quantity')
    op.drop_column('paper_orders', 'direction')
    op.drop_column('paper_orders', 'risk_decision_id')
    op.drop_column('paper_orders', 'asset_id')
    op.drop_column('execution_modes', 'allows_live_orders')
    op.drop_column('execution_modes', 'requires_approval')
    op.alter_column('approval_requests', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approval_status_enum'),
               existing_nullable=False)
    op.alter_column('approval_requests', 'signal_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('approval_requests', 'expired_at')
    op.drop_column('approval_requests', 'rejected_by')
    op.drop_column('approval_requests', 'approved_at')
    op.drop_column('approval_requests', 'approved_by')
    op.drop_column('approval_requests', 'timestamp')
    op.drop_column('approval_requests', 'risk_decision_id')
    # ### end Alembic commands ###
